export const COMMENTS = [
  {
    id: 0,
    dishId: "5f37c28ffcc031ccec6c3556",
    rating: 5,
    comment: "Imagine all the eatables, living in conFusion!",
    author: "Arslan riaz",
    date: "2019-10-16",
  },
  {
    id: 1,
    dishId: "5f37c28ffcc031ccec6c3556",
    rating: 4,
    comment:
      "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
    author: "Maheen saleemi",
    date: "2019-09-05",
  },
  {
    id: 2,
    dishId: "5f37c28ffcc031ccec6c3556",
    rating: 3,
    comment: "Eat it, just eat it!",
    author: "Ghazanfar Hassan",
    date: "2019-02-13",
  },
  {
    id: 3,
    dishId: "5f37c28ffcc031ccec6c3556",
    rating: 4,
    comment: "Ultimate, Reaching for the stars!",
    author: "Imitsal",
    date: "2019-12-02",
  },
  {
    id: 4,
    dishId: "5f37c28ffcc031ccec6c3556",
    rating: 2,
    comment: "It's your birthday, we're gonna party!",
    author: "Imran Khan",
    date: "2019-12-02",
  },
  {
    id: 5,
    dishId: 1,
    rating: 5,
    comment: "Imagine all the eatables, living in conFusion!",
    author: "Hamza Ali",
    date: "2019-10-16",
  },
  {
    id: 6,
    dishId: 1,
    rating: 4,
    comment:
      "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
    author: "Iqra Aziz",
    date: "2019-09-05",
  },
  {
    id: 7,
    dishId: 1,
    rating: 3,
    comment: "Eat it, just eat it!",
    author: "Fatima zulfiqar",
    date: "2019-02-13",
  },
  {
    id: 8,
    dishId: 1,
    rating: 4,
    comment: "Ultimate, Reaching for the stars!",
    author: "Lyba butt",
    date: "2019-12-02",
  },
  {
    id: 9,
    dishId: 1,
    rating: 2,
    comment: "It's your birthday, we're gonna party!",
    author: "Rameen Chisti",
    date: "2019-12-02",
  },
  {
    id: 10,
    dishId: 2,
    rating: 5,
    comment: "Imagine all the eatables, living in conFusion!",
    author: "Fahad Manzoor",
    date: "2019-10-16",
  },
  {
    id: 11,
    dishId: 2,
    rating: 4,
    comment:
      "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
    author: "Maryam ali",
    date: "2019-09-05",
  },
  {
    id: 12,
    dishId: 2,
    rating: 3,
    comment: "Eat it, just eat it!",
    author: "Zara butt",
    date: "2019-02-13",
  },
  {
    id: 13,
    dishId: 2,
    rating: 4,
    comment: "Ultimate, Reaching for the stars!",
    author: "Mudassir Wakeel",
    date: "2019-12-02",
  },
  {
    id: 14,
    dishId: 2,
    rating: 2,
    comment: "It's your birthday, we're gonna party!",
    author: "Umair Ali",
    date: "2019-12-02T17:57:28.556094Z",
  },
  {
    id: 15,
    dishId: 3,
    rating: 5,
    comment: "Imagine all the eatables, living in conFusion!",
    author: "Umair Chatha",
    date: "2019-10-16",
  },
  {
    id: 16,
    dishId: 3,
    rating: 4,
    comment:
      "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
    author: "Maheen Thakur",
    date: "2019-09-05",
  },
  {
    id: 17,
    dishId: 3,
    rating: 3,
    comment: "Eat it, just eat it!",
    author: "Maham rajpoot",
    date: "2019-02-13",
  },
  {
    id: 18,
    dishId: 3,
    rating: 4,
    comment: "Ultimate, Reaching for the stars!",
    author: "Awaara Parinda",
    date: "2019-12-02",
  },
  {
    id: 19,
    dishId: 3,
    rating: 2,
    comment: "It's your birthday, we're gonna party!",
    author: "Ali Habib",
    date: "2019-12-02",
  },
];
